### ISSUE TITLE
add 준혁 file

### ISSUE THREAD

**Issue by happysmileboy** [happysmileboy/tapas#1]
why??
깃헙 깃 실습위해서

**Comment by minkyung0** [comment]
참잘했어요^^

**Comment by posa98** [comment]
^^*

**Comment by happysmileboy** [comment]
$ history
    1  ls
    2  cd AppData
    3  ls
    4  cd Local
    5  ls
    6  cd Programs
    7  ls
    8  cd Python
    9  ls
   10  cd Python36-32
   11  ls
   12  mkdir test
   13  ls
   14  cd test
   15  cd https://github.com/happysmileboy/piro2.git
   16  git clone https://github.com/happysmileboy/piro2.git
   17  ls
   18  git status
   19  git log
   20  ls
   21  git status
   22  git
   23  cd piro2
   24  git status
   25  git add abc.txt
   26  git add create.helloworld
   27  git status
   28  git add abc.txt
   29  git touch abc.txt
   30  git log
   31  git status
   32  git status
   33  ls
   34  touch abc.txt
   35  git status
   36  git commit -m "Add abc.txt"
   37  git config user.email t3511410@naver.com
   38  git commit -m "Add abc.txt"
   39  ls
   40  git status
   41  git add abc.txt
   42  ls
   43  git log
   44  git status
   45  git commit -m "Add abc.txt"
   46  git branch
   47  git checkout -b bugfix
   48  git branch
   49  touch bugfix.txt
   50  ls
   51  git add bugfix.txt
   52  history
   53  histtory | grep git
   54  histtory | grap git
   55  history | grep git
   56  git commit -m "Fix bug A"
   57  git remote -v
   58  git push origin bugfix
   59  cd ~
   60  git clone https://github.com/happysmileboy/tapas.git
   61  cd tapas
   62  git checkout -b junhyeok
   63  touch jun.txt
   64  ls
   65  git status
   66  git add jun.txt
   67  git status
   68  git config core.editor vi
   69  git commit
   70  git config --global user.name happysmileboy
   71  git commit
   72  git config --global
   73  git commit
   74  git config --global user.email t3511410@naver.com
   75  git config --global user.email "t3511410@naver.com"
   76  git commit
   77  git remote -v
   78  git push origin junhyeok
